#include "autonomous_paths.hpp"

void left()
{
    chassis.setPose(-47.5, 18, 90);
    correct_position(LB, &chassis, true);
    robot.intake();
    chassis.moveToPoint(-24, 24, 1000, {.maxSpeed = 70});
    pros::delay(600);
    robot.matchLoad(true);
    chassis.turnToPoint(0, 0, 700);
    chassis.moveToPoint(-8, 8, 1000, {.maxSpeed = 90});
    robot.setState(STOP);
    robot.matchLoad(false);
    chassis.waitUntilDone();
    robot.setState(L2HELPER);
    pros::delay(200);
    robot.setState(L2AUTO);
    pros::delay(1600);
    robot.intake();
    chassis.moveToPoint(-42, 48, 1200, {false});
    chassis.turnToPoint(-70, 48, 700);
    robot.matchLoad(true);
    chassis.waitUntilDone();
    correct_position(LR, &chassis, false);
    // chassis.moveToPose(-70, -48, 270, 600, {.lead = 0.6, .maxSpeed = 80, .minSpeed = 80});
    chassis.moveToPoint(-70, 48, 800, {.maxSpeed = 80});
    chassis.waitUntilDone();
    chassis.arcade(5, 0);
    pros::delay(500);
    chassis.arcade(0, 0);
    chassis.moveToPoint(-42, 48, 1000, {false});
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    correct_position(LR, &chassis, false);
    robot.matchLoad(false);
    chassis.turnToPoint(-22, 48, 900);
    chassis.moveToPoint(-22, 48, 1200);
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    robot.scoreL3();
    chassis.arcade(30, 0);
}

void left2()
{
    chassis.setPose(-47.5, 16.611, 90);
    correct_position(LB, &chassis, true);
    robot.intake();
    chassis.moveToPoint(-24, 22, 1000, {.maxSpeed = 90});
    pros::delay(600);
    robot.matchLoad(true);
    chassis.turnToPoint(-48, 48, 700);
    chassis.moveToPoint(-48, 48, 1000);
    chassis.turnToPoint(-70, 48, 700);
    chassis.moveToPoint(-70, 48, 1000);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    pros::delay(200);
    chassis.moveToPoint(-44, 48, 700, {false});
    robot.matchLoad(false);
    chassis.turnToPoint(-25, 48, 700);
    chassis.moveToPoint(-25, 48, 1000);
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    robot.scoreL3();
    pros::delay(2000);
    correct_position(LL, &chassis, false);
    chassis.moveToPoint(-48, 48, 700, {false});
    robot.intake();
    chassis.turnToPoint(-24, 31, 500);
    chassis.moveToPoint(-24, 31, 700);
    chassis.turnToPoint(-13, 42, 500);
    chassis.moveToPoint(-13, 42, 700);
    chassis.turnToHeading(90, 700);

    robot.setState(DESCORE);
    chassis.moveToPoint(-10, 42, 800);
    pros::delay(400);
    robot.setState(INTAKE);
}
void printPose()
{
    lemlib::Pose pose = chassis.getPose();
    std::cout << "X: " << pose.x << " Y: " << pose.y << " Theta: " << pose.theta << std::endl;
}
void soloAWP()
{
    chassis.setPose(-46.733, -15.607, 180);
    correct_position(LR, &chassis, true);
    chassis.moveToPoint(-48, -48, 900);
    pros::delay(300);
    correct_position(LF, &chassis, false);
    chassis.turnToPoint(-70, -48, 500);
    printPose();
    robot.matchLoad(true, false);
    robot.setState(BACKINTAKE);
    chassis.waitUntilDone();
    printPose();
    correct_position(LL, &chassis, false);
    chassis.moveToPoint(-70, -48, 600, {.maxSpeed = 80});
    chassis.waitUntilDone();
    chassis.arcade(20, 0);
    pros::delay(200);
    // for (int i = 0; i < 3; i++)
    // {
    //     chassis.arcade(-50, 0);
    //     pros::delay(70);
    //     chassis.arcade(127, 0);
    //     pros::delay(150);
    // }
    chassis.waitUntilDone();
    // pros::delay(200);
    chassis.moveToPoint(-28, -48, 800, {.forwards = false, .maxSpeed = 80});
    robot.matchLoad(false);

    pros::delay(300);
    correct_position(LL, &chassis, false);
    pros::delay(100);
    robot.scoreL3(false);
    chassis.waitUntilDone();
    chassis.arcade(-30, 0);
    pros::delay(600);
    robot.intake();
    pros::delay(200);
    chassis.arcade(0, 0);
    chassis.moveToPoint(-48, -48, 500);
    correct_position(LR, &chassis, false);
    chassis.turnToPoint(-24, -32, 500);
    chassis.moveToPoint(-24, -32, 800);
    chassis.turnToPoint(-24, 24, 300);
    chassis.moveToPoint(-24, 12, 1000, {.minSpeed = 70, .earlyExitRange = 5});
    correct_position(LB, &chassis, false);
    chassis.moveToPoint(-24, 24, 700, {.maxSpeed = 90});
    robot.matchLoad(true);
    correct_position(LL, &chassis, true);
    chassis.turnToPoint(0, 3, 700);
    chassis.moveToPoint(-12, 14, 700, {.minSpeed = 100});
    chassis.waitUntilDone();
    robot.setState(L2HELPER);
    pros::delay(200);
    robot.setState(L2AUTO);
    pros::delay(1200);
    robot.setState(BACKINTAKE);
    chassis.moveToPoint(-43, 48, 1200, {false});
    pros::delay(400);
    chassis.turnToPoint(-70, 48, 700);
    robot.setState(BACKINTAKE);
    chassis.waitUntilDone();
    correct_position(LL, &chassis, false);
    chassis.moveToPose(-70, 48, 270, 600, {.lead = 0.8, .maxSpeed = 70, .minSpeed = 70});
    chassis.waitUntilDone();
    chassis.arcade(20, 0);
    pros::delay(300);
    correct_position(LL, &chassis, false);
    chassis.moveToPoint(-28, 48, 800, {.forwards = false, .maxSpeed = 90});
    robot.matchLoad(false);
    pros::delay(300);
    correct_position(LL, &chassis, false);
    robot.scoreL3(false);
    chassis.arcade(-30, 0);
}

void right()
{
    chassis.setPose(-47.5, -16.611, 90);
    correct_position(LB, &chassis, true);
    robot.intake();
    chassis.moveToPoint(-24, -24, 1000, {.maxSpeed = 70});
    pros::delay(600);
    robot.matchLoad(true);
    chassis.turnToPoint(0, 0, 700);
    chassis.moveToPoint(-9, -9, 1000);
    robot.setState(STOP);
    robot.matchLoad(false);
    chassis.waitUntilDone();
    robot.scoreL1();
    pros::delay(1800);
    robot.intake();
    chassis.moveToPoint(-42, -48, 1200, {false});
    chassis.turnToPoint(-70, -48, 700);
    robot.matchLoad(true);
    chassis.waitUntilDone();
    correct_position(LL, &chassis, false);
    // chassis.moveToPose(-70, -48, 270, 600, {.lead = 0.6, .maxSpeed = 80, .minSpeed = 80});
    chassis.moveToPoint(-70, -48, 600, {.maxSpeed = 100});
    chassis.waitUntilDone();
    chassis.arcade(5, 0);
    pros::delay(500);
    chassis.arcade(0, 0);
    chassis.moveToPoint(-42, -48, 1000, {false});
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    correct_position(LL, &chassis, false);
    robot.matchLoad(false);
    chassis.turnToPoint(-22, -52, 900);
    chassis.moveToPoint(-22, -49, 1200);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    robot.scoreL3();
}

void right2()
{
    chassis.setPose(-47.5, -16.611, 90);
    correct_position(LB, &chassis, true);
    robot.intake();
    chassis.moveToPoint(-24, -22, 1000, {.maxSpeed = 90});
    pros::delay(600);
    robot.matchLoad(true);
    chassis.turnToPoint(-48, -48, 700);
    chassis.moveToPoint(-48, -48, 1000);
    chassis.turnToPoint(-70, -48, 700);
    chassis.moveToPoint(-70, -48, 1000);
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    pros::delay(200);
    chassis.moveToPoint(-44, -48, 700, {false});
    robot.matchLoad(false);
    chassis.turnToPoint(-25, -48, 700);
    chassis.moveToPoint(-25, -48, 1000);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    robot.scoreL3();
    pros::delay(2000);
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(-48, -48, 700, {false});
    robot.intake();
    chassis.turnToPoint(-24, -31, 500);
    chassis.moveToPoint(-24, -31, 700);
    chassis.turnToPoint(-13, -42, 500);
    chassis.moveToPoint(-13, -42, 700);
    chassis.turnToHeading(90, 700);

    robot.setState(DESCORE);
    chassis.moveToPoint(-10, -42, 800);
    pros::delay(400);
    robot.setState(INTAKE);
}

void skills()
{
    colourSortOn = false;

    chassis.setPose(-48, 17, 0);
    correct_position(LL, &chassis, true);
    chassis.moveToPoint(-48, 48, 1000);
    chassis.waitUntilDone();
    correct_position(LF, &chassis, false);
    chassis.turnToPoint(-70, 48, 700);
    robot.matchLoad(true);
    chassis.waitUntilDone();
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(-70, 48, 1000, {.maxSpeed = 50});
    chassis.waitUntilDone();
    chassis.arcade(10, 0);
    correct_position(LF, &chassis, true);
    pros::delay(1700);
    chassis.moveToPoint(-48, 48, 1000, {false});
    robot.matchLoad(false);
    chassis.moveToPoint(-31, 60, 900, {.forwards = false});
    pros::delay(400);
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(30, 65, 1000, {.forwards = false});
    chassis.moveToPoint(48, 48, 1000, {.forwards = false});
    chassis.turnToPoint(25, 49, 900);
    chassis.waitUntilDone();
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(25, 49, 900);
    chassis.waitUntilDone();
    robot.setState(L3HELPER);
    pros::delay(200);
    robot.scoreL3();
    correct_position(LR, &chassis, false);
    pros::delay(2800);
    chassis.moveToPoint(44, 48, 900, {false});
    chassis.turnToPoint(70, 48, 900);
    robot.matchLoad(true);
    chassis.moveToPoint(70, 48, 1000, {.maxSpeed = 50});
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    chassis.arcade(5, 0);
    correct_position(LF, &chassis, true);
    pros::delay(1700);
    chassis.moveToPoint(48, 48, 900, {false});
    robot.matchLoad(false);
    chassis.turnToPoint(24, 24, 700);
    chassis.moveToPoint(24, 24, 900);
    chassis.moveToPoint(48, 48, 900, {false});
    chassis.turnToPoint(25, 48, 900);
    chassis.moveToPoint(25, 48, 1000);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    robot.setState(L3HELPER);
    pros::delay(200);
    robot.scoreL3();
    pros::delay(2800);
    chassis.moveToPoint(40, 48, 700, {false});
    robot.intake();
    chassis.turnToPoint(40, -48, 900);
    chassis.moveToPoint(40, -48, 2400);
    pros::delay(400);
    correct_position(LL, &chassis, true);
    // chassis.turnToPoint(60, 24, 700);
    // chassis.moveToPoint(62, 24, 700);
    // chassis.moveToPoint(60, -24, 1000);
    // chassis.moveToPoint(48, -48, 1000);
    pros::delay(400);
    correct_position(LF, &chassis, false);
    chassis.waitUntilDone();
    correct_position(LF, &chassis, false);
    chassis.turnToPoint(70, -48, 700);
    robot.matchLoad(true);
    chassis.moveToPoint(70, -48, 1000, {.maxSpeed = 80});
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    chassis.arcade(20, 0);
    correct_position(LF, &chassis, true);
    pros::delay(2200);
    chassis.moveToPoint(48, -48, 700, {false});
    robot.matchLoad(false);
    chassis.moveToPoint(31, -61, 900, {.forwards = false});
    pros::delay(400);
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(-30, -65, 1000, {.forwards = false});
    pros::delay(400);
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(-48, -48, 900, {.forwards = false});
    chassis.turnToPoint(-25, -48, 700);
    chassis.moveToPoint(-25, -48, 700);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    robot.setState(L3HELPER);
    pros::delay(200);
    robot.scoreL3();
    pros::delay(2300);
    chassis.moveToPoint(-44, -48, 900, {false});
    chassis.turnToPoint(-70, -48, 900);
    robot.matchLoad(true);
    chassis.moveToPoint(-70, -48, 1000, {.maxSpeed = 70});
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    chassis.arcade(30, 0);
    correct_position(LF, &chassis, true);
    pros::delay(1700);
    chassis.moveToPoint(-48, -48, 700, {false});
    correct_position(LL, &chassis, false);
    robot.matchLoad(false);
    chassis.turnToPoint(-24, -24, 700);
    chassis.moveToPoint(-24, -24, 900);
    chassis.moveToPoint(-48, -48, 900, {false});
    chassis.turnToPoint(-26, -48, 700);
    chassis.moveToPoint(-26, -48, 700);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    robot.setState(L3HELPER);
    pros::delay(200);
    robot.scoreL3();
    pros::delay(2800);
    chassis.moveToPoint(-48, -48, 700, {false});
    chassis.turnToPoint(-60, -28, 700);
    chassis.moveToPoint(-60, -28, 800);
    chassis.moveToPoint(-65, 0, 4000);
    // robot.matchLoad(true);
}

void riskySkills()
{
    colourSortOn = false;
    chassis.setPose(-48, 17, 0);
    correct_position(LL, &chassis, true);
    chassis.moveToPoint(-48, 48, 1000);
    chassis.waitUntilDone();
    correct_position(LF, &chassis, false);
    chassis.turnToPoint(-70, 48, 700);
    robot.matchLoad(true);
    chassis.waitUntilDone();
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(-70, 48, 1000, {.maxSpeed = 50});
    chassis.waitUntilDone();
    chassis.arcade(10, 0);
    correct_position(LF, &chassis, true);
    pros::delay(1200);
    chassis.moveToPoint(-48, 48, 800, {false});
    robot.matchLoad(false);
    chassis.moveToPoint(-31, 60, 900, {.forwards = false});
    pros::delay(400);
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(30, 65, 1000, {.forwards = false});
    chassis.moveToPoint(48, 48, 1000, {.forwards = false});
    chassis.turnToPoint(24, 24, 500);
    chassis.moveToPoint(24, 24, 1200, {.maxSpeed = 90});
    chassis.moveToPoint(44, 48, 900, {false});
    chassis.turnToPoint(25, 49, 700);
    chassis.waitUntilDone();
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(23, 49, 900);
    chassis.waitUntilDone();
    robot.setState(L3HELPER);
    pros::delay(200);
    robot.setState(L3);
    correct_position(LR, &chassis, false);
    pros::delay(2800);
    chassis.moveToPoint(33, 48, 900, {false});
    chassis.waitUntilDone();
    robot.setState(STOP);
    chassis.moveToPoint(23, 49, 1000, {.maxSpeed = 50});
    chassis.moveToPoint(44, 48, 900, {false});
    correct_position(LR, &chassis, false);
    chassis.turnToPoint(70, 48, 900);
    robot.matchLoad(true);
    chassis.moveToPoint(70, 48, 1000, {.maxSpeed = 60});
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    chassis.arcade(5, 0);
    colourSortOn = true;
    isRedTeam = true;
    correct_position(LF, &chassis, true);
    pros::delay(1500);
    chassis.moveToPoint(48, 48, 900, {false});
    robot.matchLoad(false);
    chassis.turnToPoint(65, 28, 500);
    chassis.moveToPoint(65, 28, 900);
    chassis.turnToPoint(69, -28, 700);
    chassis.waitUntilDone();
    correct_position(LL, &chassis, true);
    chassis.moveToPoint(69, -28, 2000, {.maxSpeed = 100});
    pros::delay(400);
    correct_position(LL, &chassis, true);
    chassis.turnToHeading(210, 700);
    correct_position(LF, &chassis, false);
    correct_position(LL, &chassis, true);
    chassis.turnToPoint(24, -24, 700);
    chassis.moveToPoint(24, -24, 1000);
    chassis.turnToPoint(0, 0, 700);
    chassis.moveToPoint(9, -9, 1000, {.maxSpeed = 60});
    chassis.waitUntilDone();
    robot.setState(L2HELPER);
    pros::delay(200);
    robot.setState(L2SKILLS);
    pros::delay(4000);
    robot.setState(INTAKE);
    colourSortOn = false;
    chassis.moveToPoint(44, -48, 1000, {false});
    chassis.turnToPoint(70, -48, 700);
    robot.matchLoad(true);
    chassis.waitUntilDone();
    correct_position(LR, &chassis, false);
    chassis.moveToPose(70, -48, 90, 1000, {.lead = 0.8, .maxSpeed = 80, .minSpeed = 80});
    chassis.waitUntilDone();
    chassis.arcade(20, 0);
    correct_position(LF, &chassis, true);
    pros::delay(2200);
    chassis.moveToPoint(48, -48, 700, {false});
    robot.matchLoad(false);
    chassis.moveToPoint(31, -61, 900, {.forwards = false});
    pros::delay(400);
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(-30, -65, 1000, {.forwards = false});
    pros::delay(400);
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(-48, -48, 900, {.forwards = false});
    chassis.turnToPoint(-25, -48, 700);
    chassis.moveToPoint(-25, -48, 700);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    robot.setState(L3HELPER);
    pros::delay(200);
    robot.scoreL3();
    pros::delay(2300);
    chassis.moveToPoint(-44, -48, 900, {false});
    chassis.turnToPoint(-70, -48, 900);
    robot.matchLoad(true);
    chassis.moveToPoint(-70, -48, 1000, {.maxSpeed = 70});
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    chassis.arcade(30, 0);
    correct_position(LF, &chassis, true);
    pros::delay(1500);
    chassis.moveToPoint(-48, -48, 700, {false});
    correct_position(LL, &chassis, false);
    robot.matchLoad(false);
    chassis.turnToPoint(-24, -24, 700);
    chassis.moveToPoint(-24, -24, 900);
    chassis.moveToPoint(-48, -48, 900, {false});
    chassis.turnToPoint(-26, -48, 700);
    chassis.moveToPoint(-26, -48, 700);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    robot.setState(L3HELPER);
    pros::delay(200);
    robot.scoreL3();
    pros::delay(2800);
    chassis.moveToPoint(-48, -48, 700, {false});
    chassis.turnToPoint(-60, -28, 700);
    chassis.moveToPoint(-60, -28, 800);
    chassis.moveToPoint(-65, 0, 4000);
}

void test()
{
    chassis.setPose(0, 0, 0);
    chassis.moveToPoint(0, 48, 2000);
    chassis.turnToPoint(48, 48, 1000);
    chassis.moveToPoint(48, 48, 2000);
    chassis.turnToPoint(48, 0, 1000);
    chassis.moveToPoint(48, 0, 2000);
    chassis.turnToPoint(0, 0, 1000);
    chassis.moveToPoint(0, 0, 2000);
    chassis.turnToHeading(0, 1000);
}