#include "autonomous_paths.hpp"

void left()
{
    chassis.setPose(-47.5, 16.611, 90);
    correct_position(LB, &chassis, true);
    robot.intake();
    chassis.moveToPoint(-24, 24, 1000, {.maxSpeed = 70});
    pros::delay(600);
    robot.matchLoad(true);
    chassis.turnToPoint(0, 0, 700);
    chassis.moveToPoint(-12, 12, 800);
    chassis.waitUntilDone();
    robot.setState(L2HELPER);
    pros::delay(200);
    robot.setState(L2AUTO);
    pros::delay(500);
    robot.intake();
    chassis.moveToPoint(-48, 48, 1200, {false});
    chassis.turnToPoint(-70, 48, 700);
    chassis.moveToPoint(-70, 48, 1000);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    pros::delay(500);
    chassis.moveToPoint(-48, 48, 700, {false});
    robot.matchLoad(false);
    chassis.turnToPoint(-28, 48, 700);
    chassis.moveToPoint(-28, 48, 1000);
    chassis.waitUntilDone();
    robot.scoreL3();
}

void left2()
{
    chassis.setPose(-47.5, 16.611, 90);
    correct_position(LB, &chassis, true);
    robot.intake();
    chassis.moveToPoint(-24, 24, 1000, {.maxSpeed = 70});
    pros::delay(600);
    robot.matchLoad(true);
    chassis.turnToPoint(-48, 48, 700);
    chassis.moveToPoint(-48, 48, 1200);
    chassis.turnToPoint(-70, 48, 700);
    chassis.moveToPoint(-70, 48, 1000);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    pros::delay(200);
    chassis.moveToPoint(-48, 48, 700, {false});
    robot.matchLoad(false);
    chassis.turnToPoint(-28, 48, 700);
    chassis.moveToPoint(-28, 48, 1000);
    chassis.waitUntilDone();
    robot.scoreL3();
}
void printPose()
{
    lemlib::Pose pose = chassis.getPose();
    std::cout << "X: " << pose.x << " Y: " << pose.y << " Theta: " << pose.theta << std::endl;
}
void soloAWP()
{
    chassis.setPose(-46.733, -15.607, 180);
    correct_position(LR, &chassis, true);
    chassis.moveToPoint(-48, -48, 900);
    pros::delay(300);
    correct_position(LF, &chassis, false);
    chassis.turnToPoint(-70, -48, 500);
    printPose();
    robot.matchLoad(true, false);
    robot.setState(BACKINTAKE);
    chassis.waitUntilDone();
    printPose();
    correct_position(LL, &chassis, false);
    chassis.moveToPoint(-70, -48, 600, {.maxSpeed = 80});
    chassis.waitUntilDone();
    chassis.arcade(20, 0);
    pros::delay(200);
    // for (int i = 0; i < 3; i++)
    // {
    //     chassis.arcade(-50, 0);
    //     pros::delay(70);
    //     chassis.arcade(127, 0);
    //     pros::delay(150);
    // }
    chassis.waitUntilDone();
    // pros::delay(200);
    chassis.moveToPoint(-28, -48, 800, {false});
    robot.matchLoad(false);

    pros::delay(300);
    correct_position(LL, &chassis, false);
    robot.scoreL3(false);
    pros::delay(1000);
    robot.intake();
    chassis.moveToPoint(-48, -48, 500);
    correct_position(LR, &chassis, false);
    chassis.turnToPoint(-24, -32, 500);
    chassis.moveToPoint(-24, -32, 700);
    chassis.turnToPoint(-24, 24, 500);
    chassis.moveToPoint(-24, 12, 1200, {.minSpeed = 70, .earlyExitRange = 5});
    correct_position(LB, &chassis, false);
    chassis.moveToPoint(-24, 24, 700, {.maxSpeed = 70});
    robot.matchLoad(true);
    correct_position(LL, &chassis, true);
    chassis.turnToPoint(0, 0, 700);
    chassis.moveToPoint(-12, 12, 700, {.minSpeed = 100});
    chassis.waitUntilDone();
    robot.setState(L2HELPER);
    pros::delay(100);
    robot.setState(L2AUTO);
    pros::delay(1300);
    robot.setState(BACKINTAKE);
    robot.matchLoad(false);
    chassis.moveToPoint(-48, 48, 1200, {false});

    chassis.turnToPoint(-70, 47, 700);
    robot.matchLoad(true, false);
    robot.setState(BACKINTAKE);
    chassis.moveToPoint(-70, 48, 600, {.maxSpeed = 80});
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    chassis.arcade(20, 0);
    pros::delay(300);
    chassis.moveToPoint(-28, 48, 800, {false});
    robot.matchLoad(false);
    pros::delay(300);
    correct_position(LL, &chassis, false);
    robot.scoreL3(false);
}

void right()
{
    chassis.setPose(-47.5, -16.611, 90);
    correct_position(LB, &chassis, true);
    robot.intake();
    chassis.moveToPoint(-24, -24, 1000, {.maxSpeed = 70});
    pros::delay(600);
    robot.matchLoad(true);
    chassis.turnToPoint(0, 0, 700);
    chassis.moveToPoint(-12, -12, 800);
    robot.matchLoad(false);
    chassis.waitUntilDone();
    robot.scoreL1();
    pros::delay(700);
    robot.intake();
    chassis.moveToPoint(-48, -48, 1200, {false});
    chassis.turnToPoint(-70, -48, 700);
    robot.matchLoad(true);
    chassis.moveToPoint(-70, -48, 1000);
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    pros::delay(500);
    chassis.moveToPoint(-48, -48, 700, {false});
    robot.matchLoad(false);
    chassis.turnToPoint(-28, -48, 700);
    chassis.moveToPoint(-28, -48, 1000);
    chassis.waitUntilDone();
    robot.scoreL3();
}

void right2()
{
    chassis.setPose(-47.5, -16.611, 90);
    correct_position(LB, &chassis, true);
    robot.intake();
    chassis.moveToPoint(-24, -24, 1000, {.maxSpeed = 70});
    pros::delay(600);
    robot.matchLoad(true);
    chassis.turnToPoint(-48, -48, 700);
    chassis.moveToPoint(-48, -48, 1200);
    chassis.turnToPoint(-70, -48, 700);
    chassis.moveToPoint(-70, -48, 1000);
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    pros::delay(200);
    chassis.moveToPoint(-48, -48, 700, {false});
    robot.matchLoad(false);
    chassis.turnToPoint(-28, -48, 700);
    chassis.moveToPoint(-28, -48, 1000);
    chassis.waitUntilDone();
    robot.scoreL3();
}

void skills()
{
    colourSortOn = false;
    chassis.setPose(-48, 17, 0);
    correct_position(LL, &chassis, true);
    chassis.moveToPoint(-48, 48, 1000);
    chassis.waitUntilDone();
    correct_position(LF, &chassis, false);
    chassis.turnToPoint(-70, 48, 700);
    robot.matchLoad(true);
    chassis.moveToPoint(-70, 48, 1000, {.maxSpeed = 50});
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    chassis.arcade(5, 0);
    correct_position(LF, &chassis, true);
    pros::delay(1700);
    chassis.moveToPoint(-48, 48, 1000, {false});
    robot.matchLoad(false);
    chassis.moveToPoint(-30, 59, 900, {.forwards = false});
    pros::delay(400);
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(30, 65, 1000, {.forwards = false});
    chassis.moveToPoint(48, 48, 1000, {.forwards = false});
    chassis.turnToPoint(25, 49, 900);
    chassis.waitUntilDone();
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(25, 49, 900);
    chassis.waitUntilDone();
    robot.setState(L3HELPER);
    pros::delay(200);
    robot.scoreL3();
    correct_position(LR, &chassis, false);
    pros::delay(2800);
    chassis.moveToPoint(48, 48, 900, {false});
    chassis.turnToPoint(70, 48, 900);
    robot.matchLoad(true);
    chassis.moveToPoint(70, 48, 1000, {.maxSpeed = 50});
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    chassis.arcade(5, 0);
    correct_position(LF, &chassis, true);
    pros::delay(1700);
    chassis.moveToPoint(48, 48, 900, {false});
    robot.matchLoad(false);
    chassis.turnToPoint(24, 24, 700);
    chassis.moveToPoint(24, 24, 900);
    chassis.moveToPoint(48, 48, 900, {false});
    chassis.turnToPoint(25, 48, 900);
    chassis.moveToPoint(25, 48, 1000);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    robot.setState(L3HELPER);
    pros::delay(200);
    robot.scoreL3();
    pros::delay(2800);
    chassis.moveToPoint(40, 48, 700, {false});
    robot.intake();
    chassis.turnToPoint(40, -48, 900);
    chassis.moveToPoint(40, -48, 2400);
    pros::delay(400);
    correct_position(LL, &chassis, true);
    // chassis.turnToPoint(60, 24, 700);
    // chassis.moveToPoint(62, 24, 700);
    // chassis.moveToPoint(60, -24, 1000);
    // chassis.moveToPoint(48, -48, 1000);
    pros::delay(400);
    correct_position(LF, &chassis, false);
    chassis.waitUntilDone();
    correct_position(LF, &chassis, false);
    chassis.turnToPoint(70, -48, 700);
    robot.matchLoad(true);
    chassis.moveToPoint(70, -48, 1000, {.maxSpeed = 50});
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    chassis.arcade(5, 0);
    correct_position(LF, &chassis, true);
    pros::delay(2200);
    chassis.moveToPoint(48, -48, 700, {false});
    robot.matchLoad(false);
    chassis.moveToPoint(30, -60, 900, {.forwards = false});
    pros::delay(400);
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(-30, -65, 1000, {.forwards = false});
    pros::delay(400);
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(-48, -48, 900, {.forwards = false});
    chassis.turnToPoint(-25, -49, 700);
    chassis.moveToPoint(-25, -49, 700);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    robot.setState(L3HELPER);
    pros::delay(200);
    robot.scoreL3();
    pros::delay(2300);
    chassis.moveToPoint(-48, -48, 700, {false});
    chassis.turnToPoint(-70, -48, 700);
    robot.matchLoad(true);
    chassis.moveToPoint(-70, -48, 1000, {.maxSpeed = 60});
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    chassis.arcade(5, 0);
    correct_position(LF, &chassis, true);
    pros::delay(1700);
    chassis.moveToPoint(-48, -48, 700, {false});
    correct_position(LL, &chassis, false);
    robot.matchLoad(false);
    chassis.turnToPoint(-24, -24, 700);
    chassis.moveToPoint(-24, -24, 900);
    chassis.moveToPoint(-48, -48, 900, {false});
    chassis.turnToPoint(-26, -48, 700);
    chassis.moveToPoint(-26, -48, 700);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    robot.setState(L3HELPER);
    pros::delay(200);
    robot.scoreL3();
    pros::delay(2800);
    chassis.moveToPoint(-48, -48, 700, {false});
    chassis.turnToPoint(-60, -28, 700);
    chassis.moveToPoint(-60, -28, 800);
    chassis.moveToPoint(-65, 0, 4000);
    // robot.matchLoad(true);
}

void riskySkills()
{
    colourSortOn = false;
    chassis.setPose(-48, 17, 0);
    correct_position(LL, &chassis, true);
    chassis.moveToPoint(-48, 48, 1000);
    chassis.waitUntilDone();
    correct_position(LF, &chassis, false);
    chassis.turnToPoint(-70, 48, 700);
    robot.matchLoad(true);
    chassis.moveToPoint(-70, 48, 1000, {.maxSpeed = 50});
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    chassis.arcade(5, 0);
    correct_position(LF, &chassis, true);
    pros::delay(1700);
    chassis.moveToPoint(-48, 48, 1000, {false});
    robot.matchLoad(false);
    chassis.moveToPoint(-30, 59, 900, {.forwards = false});
    pros::delay(400);
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(30, 65, 1000, {.forwards = false});
    chassis.moveToPoint(48, 48, 1000, {.forwards = false});
    chassis.turnToPoint(25, 49, 900);
    chassis.waitUntilDone();
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(25, 49, 900);
    chassis.waitUntilDone();
    robot.setState(L3HELPER);
    pros::delay(200);
    robot.scoreL3();
    correct_position(LR, &chassis, false);
    pros::delay(2800);
    chassis.moveToPoint(48, 48, 900, {false});
    chassis.turnToPoint(70, 48, 900);
    robot.matchLoad(true);
    chassis.moveToPoint(70, 48, 1000, {.maxSpeed = 50});
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    chassis.arcade(5, 0);
    correct_position(LF, &chassis, true);
    pros::delay(1700);
    chassis.moveToPoint(25, 48, 1300, {false});
    pros::delay(300);
    robot.matchLoad(false);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    robot.setState(BACKL3);
    pros::delay(2800);
    chassis.moveToPoint(48, 48, 700, {false});
    robot.intake();
    chassis.turnToPoint(60, 24, 900);
    chassis.moveToPoint(60, 24, 1000);
    chassis.turnToPoint(60, -24, 700);
    chassis.moveToPoint(60, -24, 2000);
    pros::delay(400);
    correct_position(LL, &chassis, true);
    chassis.turnToPoint(48, -48, 700);
    correct_position(LL, &chassis, true);
    chassis.moveToPoint(48, -48, 1000);
    pros::delay(300);
    correct_position(LF, &chassis, false);

    // chassis.turnToPoint(60, 24, 700);
    // chassis.moveToPoint(62, 24, 700);
    // chassis.moveToPoint(60, -24, 1000);
    // chassis.moveToPoint(48, -48, 1000);
    pros::delay(400);
    correct_position(LF, &chassis, false);
    chassis.waitUntilDone();
    correct_position(LF, &chassis, false);
    chassis.turnToPoint(70, -48, 700);
    robot.matchLoad(true);
    chassis.moveToPoint(70, -48, 1000, {.maxSpeed = 50});
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    chassis.arcade(5, 0);
    correct_position(LF, &chassis, true);
    pros::delay(2200);
    chassis.moveToPoint(48, -48, 700, {false});
    robot.matchLoad(false);
    chassis.moveToPoint(30, -60, 900, {.forwards = false});
    pros::delay(400);
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(-30, -65, 1000, {.forwards = false});
    pros::delay(400);
    correct_position(LR, &chassis, false);
    chassis.moveToPoint(-48, -48, 900, {.forwards = false});
    chassis.turnToPoint(-25, -49, 700);
    chassis.moveToPoint(-25, -49, 700);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    robot.setState(L3HELPER);
    pros::delay(200);
    robot.scoreL3();
    pros::delay(2300);
    chassis.moveToPoint(-48, -48, 700, {false});
    chassis.turnToPoint(-70, -48, 700);
    robot.matchLoad(true);
    chassis.moveToPoint(-70, -48, 1000, {.maxSpeed = 50});
    correct_position(LL, &chassis, false);
    chassis.waitUntilDone();
    chassis.arcade(5, 0);
    correct_position(LF, &chassis, true);
    pros::delay(1700);
    chassis.moveToPoint(-48, -48, 700, {false});
    correct_position(LL, &chassis, false);
    robot.matchLoad(false);
    chassis.turnToPoint(-24, -24, 700);
    chassis.moveToPoint(-24, -24, 900);
    chassis.moveToPoint(-48, -48, 900, {false});
    chassis.turnToPoint(-26, -48, 700);
    chassis.moveToPoint(-26, -48, 700);
    correct_position(LR, &chassis, false);
    chassis.waitUntilDone();
    robot.setState(L3HELPER);
    pros::delay(200);
    robot.scoreL3();
    pros::delay(2800);
    chassis.moveToPoint(-48, -48, 700, {false});
    chassis.turnToPoint(-60, -28, 700);
    chassis.moveToPoint(-60, -28, 800);
    chassis.moveToPoint(-65, 4, 4000);
    // robot.matchLoad(true);
}

void test()
{
    chassis.setPose(0, 0, 0);
    chassis.moveToPoint(0, 48, 2000);
    chassis.turnToPoint(48, 48, 1000);
    chassis.moveToPoint(48, 48, 2000);
    chassis.turnToPoint(48, 0, 1000);
    chassis.moveToPoint(48, 0, 2000);
    chassis.turnToPoint(0, 0, 1000);
    chassis.moveToPoint(0, 0, 2000);
    chassis.turnToHeading(0, 1000);
}